### PR TITLE
Fix TikTokURLOpener UIApplication Conformance on Xcode 16 Beta 3

### PR DESCRIPTION
**Pull request by wendyliga**
as title described

### CODE REVIEW

**Comment by wendyliga** [comment]
@GuidoPu please help check this PR :pray:

**Comment by Frizlab** [comment]
While this technically works, I would personally recommend against this fix and use a proper one instead (not making external types conform to an internal protocol).

When using this fix, I had another issue when calling `applicationInstance.open(url, options: [:], completionHandler: nil)`: `Ambiguous use of 'open(_:options:completionHandler:)'`.

This is due to the completionHandler parameter having two possible types now: `(@MainActor @Sendable (Bool) -> Void)?` and `((Bool) -> Void)?`.
To fix _this_ issue one has now to call the `open` method using `open(url, options: [:], completionHandler: nil as (@MainActor @Sendable (Bool) -> Void)?)`, which is terrible.

**Comment by WineKai** [comment]
> While this technically works, I would personally recommend against this fix and use a proper one instead (not making external types conform to an internal protocol).
> 
> When using this fix, I had another issue when calling `applicationInstance.open(url, options: [:], completionHandler: nil)`: `Ambiguous use of 'open(_:options:completionHandler:)'`.
> 
> This is due to the completionHandler parameter having two possible types now: `(@MainActor @Sendable (Bool) -> Void)?` and `((Bool) -> Void)?`. To fix _this_ issue one has now to call the `open` method using `open(url, options: [:], completionHandler: nil as (@MainActor @Sendable (Bool) -> Void)?)`, which is terrible.

So how did you fix that?

**Comment by Frizlab** [comment]
@WineKai I invite you to read literally the last sentence of the message you’re replying to: it’s the fix.

**Comment by larryonoff** [comment]
Guys. Did you check the latest release [2.5.0](https://github.com/tiktok/tiktok-opensdk-ios/releases/tag/v2.5.0)? Xcode 16.0 works for me

**Comment by Frizlab** [comment]
Confirmed, 2.5 works.

**Comment by WineKai** [comment]
> @WineKai I invite you to read literally the last sentence of the message you’re replying to: it’s the fix.

Ha ha ha, I see it. Thanks

**Pull request closed without merging**
